import { INotification } from "./types/discussions";

export const DummydataList: INotification[] | undefined = [
  {
    loading: true,
    resourceId: 0,

    tagComment: 0,
    tagCommentId: 0,
    title: "",
    toUserId: "",
    updatedAt: new Date(),

    createdAt: new Date(),
    id: 0,
    isView: true,
    description: "",
    fromUser: {
      name: "",
      image: "",
    },
    fromUserId: "",
    commentId: 0,
    notificationType: "COMMENT",
    comment: {
      id: 0,
      userId: "",
      resourceId: 0,
      tagCommentId: null,
      comment: null,
      attachedFiles: null,
      parentCommentId: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    resource: {
      resourceId: 0,
      chapterId: 0,
      chapter: {
        courseId: 0,
      },
    },
  },
  {
    loading: true,
    resourceId: 0,

    tagComment: 0,
    tagCommentId: 0,
    title: "",
    toUserId: "",
    updatedAt: new Date(),

    createdAt: new Date(),
    id: 0,
    isView: true,
    description: "",
    fromUser: {
      name: "",
      image: "",
    },
    fromUserId: "",
    commentId: 0,
    notificationType: "COMMENT",
    comment: {
      id: 0,
      userId: "",
      resourceId: 0,
      tagCommentId: null,
      comment: null,
      attachedFiles: null,
      parentCommentId: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    resource: {
      resourceId: 0,
      chapterId: 0,
      chapter: {
        courseId: 0,
      },
    },
  },
  {
    loading: true,
    resourceId: 0,

    tagComment: 0,
    tagCommentId: 0,
    title: "",
    toUserId: "",
    updatedAt: new Date(),

    createdAt: new Date(),
    id: 0,
    isView: true,
    description: "",
    fromUser: {
      name: "",
      image: "",
    },
    fromUserId: "",
    commentId: 0,
    notificationType: "COMMENT",
    comment: {
      id: 0,
      userId: "",
      resourceId: 0,
      tagCommentId: null,
      comment: null,
      attachedFiles: null,
      parentCommentId: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    resource: {
      resourceId: 0,
      chapterId: 0,
      chapter: {
        courseId: 0,
      },
    },
  },
  {
    loading: true,
    resourceId: 0,

    tagComment: 0,
    tagCommentId: 0,
    title: "",
    toUserId: "",
    updatedAt: new Date(),

    createdAt: new Date(),
    id: 0,
    isView: true,
    description: "",
    fromUser: {
      name: "",
      image: "",
    },
    fromUserId: "",
    commentId: 0,
    notificationType: "COMMENT",
    comment: {
      id: 0,
      userId: "",
      resourceId: 0,
      tagCommentId: null,
      comment: null,
      attachedFiles: null,
      parentCommentId: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    resource: {
      resourceId: 0,
      chapterId: 0,
      chapter: {
        courseId: 0,
      },
    },
  },
  {
    loading: true,
    resourceId: 0,

    tagComment: 0,
    tagCommentId: 0,
    title: "",
    toUserId: "",
    updatedAt: new Date(),

    createdAt: new Date(),
    id: 0,
    isView: true,
    description: "",
    fromUser: {
      name: "",
      image: "",
    },
    fromUserId: "",
    commentId: 0,
    notificationType: "COMMENT",
    comment: {
      id: 0,
      userId: "",
      resourceId: 0,
      tagCommentId: null,
      comment: null,
      attachedFiles: null,
      parentCommentId: null,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    resource: {
      resourceId: 0,
      chapterId: 0,
      chapter: {
        courseId: 0,
      },
    },
  },
];
