#!/bin/bash
cd /opt/torqbit
pm2 stop $2
rm -rf torq


git clone https://amezng:${GH_TOKEN}@github.com/torqbit/torq.git
cd torq
git fetch --all
git checkout $1

touch .env

cat <<EOF >> .env
GITHUB_ID=$GITHUB_ID
GITHUB_SECRET=$GITHUB_SECRET
NEXT_PUBLIC_EMAIL_ADDRESS=$NEXT_PUBLIC_EMAIL_ADDRESS
NEXT_PUBLIC_PASSWORD=$NEXT_PUBLIC_PASSWORD
FROM_USER_EMAIL=$FROM_USER_EMAIL
TO_USER_EMAIL=
DATABASE_URL=$DATABASE_URL
NEXT_PUBLIC_SECRET=$NEXT_PUBLIC_SECRET
NEXTAUTH_URL=$NEXTAUTH_URL
NEXT_PUBLIC_APP_ENV=$NEXT_PUBLIC_APP_ENV
.NODE_ENV=$NODE_ENV
MEDIA_UPLOAD_PATH=$MEDIA_UPLOAD_PATH
GOOGLE_ID=$GOOGLE_ID
GOOGLE_SECRET=$GOOGLE_SECRET
IKIT_PUBLIC_KEY=$IKIT_PUBLIC_KEY
IKIT_PRIVATE_KEY=$IKIT_PRIVATE_KEY
IKIT_URL_ENDPOINT=$IKIT_URL_ENDPOINT
IKIT_AUTH_ENDPOINT=$IKIT_AUTH_ENDPOINT
PDF_DIRECTORY=$PDF_DIRECTORY
NEXT_SMTP_HOST=$NEXT_SMTP_HOST
NEXT_SMTP_USER=$NEXT_SMTP_USER
NEXT_SMTP_PASSWORD=$NEXT_SMTP_PASSWORD

EOF
yarn install
npx prisma generate
npx prisma db push
yarn build
cp -R .next/static/ /var/www/console/.next
pm2 start $2