version: "3"

services:
  web:
    image: torqbit:v1
    ports:
      - "3000:3000"
    build: .
    command: ["sh", "-c", "npx prisma db push --accept-data-loss && cat ascii && yarn start"]

    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/user/get-all || exit 1"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 10s

    env_file:
      - "./docker.env"

    networks:
      - app-network

  db:
    image: mysql:8.0
    hostname: db.torqbit.com
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "mysqladmin -uroot -pMehrab@123 status && mysql -uroot -pMehrab@123 -e 'USE console; SHOW TABLES ; SELECT * FROM User;'",
        ]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 10s
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Mehrab@123
      MYSQL_DATABASE: console
    volumes:
      - db-data:/var/lib/mysql
      - /c/Users/mehra/training/database_backup:/backups

    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
