export type IEmailEventType =
  | "NEW_USER"
  | "COURSE_ENROLMENT"
  | "COURSE_COMPLETION"
  | "FEEDBACK"
  | "NEW_LESSON"
  | "ASSIGNMENT_SUBMISSION"
  | "EVENT_COMPLETION"
  | "GRANT_ACCESS"
  | "DENIED_ACCESS"
  | "ASSIGNMENT_COMPLETION";
